#!/bin/sh
cd /webapps/code/zeligproject.org
git status
git pull
echo "Updating R packages"
sudo /webapps/code/zeligproject.org/deploy/update-R-packages
echo "Build Sphinx docs using Python 2.7"
scl enable python27 '/webapps/code/zeligproject.org/deploy/post-build2'
echo "Done"
